name: 17-3-2 クロスリポジトリアクセス
on: workflow_dispatch
defaults:
  run:
    shell: bash
env:
  TARGET_REPO: practice-github-actions2
jobs:
  access:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - id: create
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          repositories: ${{ secrets.TARGET_REPO }}
          # owner: ${{ github.repository.owner }}
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner}}/${{env.TARGET_REPO}}
          path: ${{ env.TARGET_REPO }}
          token: ${{ steps.create.outputs.token }}
          ref: main
      - run: cat "${TARGET_REPO}/README.md"
