name: 3-3 secrets and variables
description: use secrets and variables from both environment and repository scope.
on: workflow_dispatch
jobs:
  print-secrets-and-variables:
    runs-on: ubuntu-latest
    environment: env01
    env:
      ENV_SECRET_1: ${{ secrets.ENV_SECRET_1 }}
      ENV_VAR_1: ${{ vars.ENV_VAR_1 }}
      REPO_SECRET_1: ${{ secrets.REPO_SECRET_1 }}
      REPO_VAR_1: ${{ vars.REPO_VAR_1 }}
    steps:
      - run: echo "${ENV_SECRET_1}"
      - run: echo "${ENV_VAR_1}"
      - run: echo "${REPO_SECRET_1}"
      - run: echo "${REPO_VAR_1}"
