name: CI
description: Node.jsのプログラムのCI用ワークフロー
on: push
jobs:
  ci:
    runs-on: ubuntu-latest
    # ジョブ内のすべての run ステップのデフォルト作業ディレクトリを固定
    defaults:
      run:
        working-directory: ./4-2_src
    steps:
      - uses: actions/checkout@v7
      - run: npm install
      - run: npm run lint
      - run: npm test
