name: CI
description: Node.jsのプログラムのCI用ワークフロー
on: push
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pwd
      - run: ls
      - run: node 4-2_src/test.bash
