name: 4-8-2 Concurrency
on: workflow_dispatch
concurrency: 
  group: ${{ github.workflow }}
  cancel-in-progress: true
defaults:
  run:
    shell: bash
jobs:
  auto-cancel-experiment:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - run: sleep 20
