name: 6-3-5 JS Action
on: workflow_dispatch
jobs:
  use-js-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cd .github/actions/js-action-sample && npm install
      - uses: ./.github/actions/js-action-sample
        id: js
        with:
          who-to-great: 'Taro'
      - run: echo "${TIME}"
        env:
          TIME: ${{ steps.js.outputs.time }}
