name: Context
description: Try to use various context of github actions
on: push
jobs:
    print-context:
        runs-on: ubuntu-latest
        steps:
            - run: echo "github.actor - ${{ github.actor }}"
            - run: echo "github.run_id - ${{ github.run_id }}"
            - run: echo "github.head_ref - ${{ github.head_ref }}"
            - run: echo "github.event - ${{ github.event }}"
            - run: echo "github.event.push - ${{ github.event.pusher }}"
            - run: echo "github.event.pusher.name - ${{ github.event.pusher.name }}"