name: secrets and variables
on: push
jobs:
  print-secrets-and-variables:
    runs-on: ubuntu-latest
    environment: env01
    env:
      ENV_SECRET_1: ${{ vars.ENV_SECRET_1 }}
      ENV_VAR_1: ${{ vars.ENV_VAR_1 }}
      REPO_SECRET_1: ${{ secrets.REPO_SECRET_1 }}
      REPO_VAR_1: ${{ secrets.REPO_VAR_1 }}
    steps:
      - run: echo "${ENV_SECRET_1}"
      - run: echo "${ENV_VAR_1}"
      - run: echo "${REPO_SECRET_1}"
      - run: echo "${REPO_VAR_1}"
