name: 中間環境変数の実験
description: インジェクションされた環境変数のスコープを確認するためのワークフロー
on: push
env:
    EXAMPLE: Defined by workflow level
jobs:
    print-context:
        runs-on: ubuntu-latest
        steps:
            - name: GITHUB_OUTPUTに値を埋め込む
              id : my_id
              run: echo "my_key=\"; date;\"" >> $GITHUB_OUTPUT
            - name: 直に参照する（危険）
              run: echo "${{ steps.my_id.outputs.my_key }}"
            - name: 安全に参照する
              env:
                MY_ENV: ${{ steps.my_id.outputs.my_key }}
              run: echo "${MY_ENV}"
